Issue #102
jenkinsci/peass-ci-plugin pull request #105
Opened 2022-02-28 15:25 UTC by Schattensilber

Uses partial success status for runs where some RTS runs failed, uses failure status for runs where all RTS runs fail
See [https://github.com/jenkinsci/peass-ci-plugin/issues/102](url)

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-02-28 23:27 UTC, DaGeRe requested changes
Please adapt your changes to the current code style (or close this PR and create a new PR with the correct code style). You can find the style here: https://github.com/DaGeRe/peass/blob/main/misc/peassstyle.xml

2022-02-28 23:27 UTC, DaGeRe commented on src/main/java/de/dagere/peass/ci/logs/rts/AggregatedRTSResult.java
> -   private final RTSLogSummary logSummary;
Please do not reform the code, since this will create a lot of boilerplate changes in the version history

2022-02-28 23:27 UTC, DaGeRe commented on src/main/java/de/dagere/peass/ci/logs/rts/AggregatedRTSResult.java
> +	private final RTSLogSummary logSummary;
Same here and in all subsequent lines with formatting changes

2022-03-01 13:03 UTC, Schattensilber commented
I have changed the code style as requested.
Some whitespaces in empty lines are still changed, but in accordance with the code style, so I assume they are beneficial.

2022-03-01 14:57 UTC, merged